import type {
  ChatMessage,
  OpportunityProtocolConfig,
  SignalWeightKey,
  SurveyData,
} from "./types";

export const signalWeightLabels: Record<SignalWeightKey, string> = {
  skillFit: "Skill fit",
  localDemand: "Local demand",
  wageFloor: "Wage signal",
  growth: "Growth",
  automationResilience: "AI resilience",
  trainingAccess: "Training access",
};

export const initialOpportunityProtocols: OpportunityProtocolConfig[] = [
  {
    id: "ghana-urban-informal",
    version: "opportunity-protocol-v0.1",
    contextName: "Ghana · urban informal repair",
    countryCode: "GH",
    region: "Greater Accra",
    locale: "en-GH",
    language: "English",
    currency: "GHS",
    educationTaxonomy: "Ghana SHS / TVET / informal apprenticeship",
    opportunityTypes: [
      "formal employment",
      "self-employment",
      "apprenticeship",
      "short training",
    ],
    automationCalibration:
      "Lower digital infrastructure and high in-person service demand reduce near-term substitution for repair and customer-facing work.",
    signalWeights: {
      skillFit: 36,
      localDemand: 18,
      wageFloor: 12,
      growth: 12,
      automationResilience: 12,
      trainingAccess: 10,
    },
    sources: [
      {
        id: "ilostat",
        label: "Employment and youth labor indicators",
        provider: "ILO",
        dataset: "ILOSTAT",
        year: "latest admin upload",
        updateCycle: "annual",
        status: "needs_upload",
      },
      {
        id: "wdi",
        label: "Macro and education context",
        provider: "World Bank",
        dataset: "World Development Indicators",
        year: "latest admin upload",
        updateCycle: "annual",
        status: "needs_upload",
      },
      {
        id: "local-jobs",
        label: "Local vacancies and training places",
        provider: "Program partner",
        dataset: "CSV / API feed",
        year: "pilot sample",
        updateCycle: "monthly",
        status: "demo",
      },
      {
        id: "itu",
        label: "Connectivity constraint",
        provider: "ITU",
        dataset: "Digital Development indicators",
        year: "latest admin upload",
        updateCycle: "annual",
        status: "needs_upload",
      },
    ],
    econometricSignals: [
      {
        id: "youth_neet",
        category: "Youth employment",
        label: "Youth not in employment, education, or training",
        value: "admin upload",
        unit: "% of youth",
        sourceId: "ilostat",
        year: "latest",
        interpretation:
          "High values push the matching layer toward reachable entry routes and training-linked work.",
        userVisible: true,
      },
      {
        id: "services_employment",
        category: "Sector structure",
        label: "Employment in services",
        value: "admin upload",
        unit: "% of employment",
        sourceId: "ilostat",
        year: "latest",
        interpretation:
          "Service-sector weight helps rank repair, retail, customer support, and field-service routes.",
        userVisible: true,
      },
      {
        id: "mobile_broadband",
        category: "Digital constraint",
        label: "Mobile broadband access",
        value: "admin upload",
        unit: "subscriptions / 100 people",
        sourceId: "itu",
        year: "latest",
        interpretation:
          "Connectivity changes how realistic remote digital work is for the local context.",
        userVisible: true,
      },
    ],
    opportunities: [
      {
        id: "mobile-repair-technician",
        title: "Mobile phone repair technician",
        sector: "repair services",
        opportunityType: "self-employment or shop employment",
        iscoGroup: "7422",
        locationFit: "urban and peri-urban repair markets",
        requiredEducation: "SHS or informal apprenticeship",
        skillKeywords: [
          "phone repair",
          "diagnosing charging problems",
          "replacing screens",
          "customer communication",
          "keeping records",
        ],
        demandLevel: 4,
        wageFloorSignal: 3,
        wageFloor: "admin local wage floor",
        growthOutlook: 3,
        automationExposure: 1,
        trainingAccess: 4,
        trainingPathway: "repair apprenticeship, TVET short module, parts vendor network",
        sourceIds: ["local-jobs", "ilostat"],
      },
      {
        id: "device-support-assistant",
        title: "Device support and customer service assistant",
        sector: "retail and repair services",
        opportunityType: "formal employment",
        iscoGroup: "5249",
        locationFit: "phone shops, electronics retail, call-in support desks",
        requiredEducation: "SHS plus customer-facing experience",
        skillKeywords: [
          "customer communication",
          "phone repair",
          "records",
          "basic html",
          "javascript",
        ],
        demandLevel: 3,
        wageFloorSignal: 3,
        wageFloor: "admin local wage floor",
        growthOutlook: 3,
        automationExposure: 2,
        trainingAccess: 3,
        trainingPathway: "retail service onboarding and basic digital-support certificate",
        sourceIds: ["local-jobs", "ilostat", "itu"],
      },
      {
        id: "junior-web-maintenance",
        title: "Junior web maintenance assistant",
        sector: "digital services",
        opportunityType: "remote or local gig",
        iscoGroup: "3514",
        locationFit: "requires reliable mobile broadband and portfolio evidence",
        requiredEducation: "portfolio accepted; certificate helpful",
        skillKeywords: [
          "html",
          "javascript",
          "records",
          "customer communication",
        ],
        demandLevel: 2,
        wageFloorSignal: 3,
        wageFloor: "admin local gig-rate sample",
        growthOutlook: 4,
        automationExposure: 3,
        trainingAccess: 3,
        trainingPathway: "portfolio tasks, web basics course, supervised small-business sites",
        sourceIds: ["local-jobs", "itu"],
      },
    ],
  },
  {
    id: "india-rural-agri",
    version: "opportunity-protocol-v0.1",
    contextName: "India · rural agricultural services",
    countryCode: "IN",
    region: "rural district pilot",
    locale: "en-IN",
    language: "English / local-language UI pack",
    currency: "INR",
    educationTaxonomy: "Class 10 / Class 12 / ITI / local training certificate",
    opportunityTypes: [
      "seasonal work",
      "self-employment",
      "field service",
      "training pathway",
    ],
    automationCalibration:
      "Mechanization risk differs by farm size, irrigation access, and local equipment availability.",
    signalWeights: {
      skillFit: 34,
      localDemand: 20,
      wageFloor: 10,
      growth: 14,
      automationResilience: 10,
      trainingAccess: 12,
    },
    sources: [
      {
        id: "ilostat",
        label: "Employment and sector status",
        provider: "ILO",
        dataset: "ILOSTAT",
        year: "latest admin upload",
        updateCycle: "annual",
        status: "needs_upload",
      },
      {
        id: "wdi",
        label: "Rural development indicators",
        provider: "World Bank",
        dataset: "World Development Indicators",
        year: "latest admin upload",
        updateCycle: "annual",
        status: "needs_upload",
      },
      {
        id: "district-feed",
        label: "District job, training, and cooperative feed",
        provider: "State / NGO partner",
        dataset: "CSV / API feed",
        year: "pilot sample",
        updateCycle: "monthly",
        status: "demo",
      },
      {
        id: "itu",
        label: "Connectivity constraint",
        provider: "ITU",
        dataset: "Digital Development indicators",
        year: "latest admin upload",
        updateCycle: "annual",
        status: "needs_upload",
      },
    ],
    econometricSignals: [
      {
        id: "agri_employment",
        category: "Sector structure",
        label: "Employment in agriculture",
        value: "admin upload",
        unit: "% of employment",
        sourceId: "ilostat",
        year: "latest",
        interpretation:
          "Agricultural employment share changes how heavily the engine ranks farm-service and equipment pathways.",
        userVisible: true,
      },
      {
        id: "youth_lfp",
        category: "Youth labor market",
        label: "Youth labor force participation",
        value: "admin upload",
        unit: "% of youth",
        sourceId: "ilostat",
        year: "latest",
        interpretation:
          "Participation levels help distinguish job scarcity from skill-recognition gaps.",
        userVisible: true,
      },
      {
        id: "mobile_broadband",
        category: "Digital constraint",
        label: "Mobile broadband access",
        value: "admin upload",
        unit: "subscriptions / 100 people",
        sourceId: "itu",
        year: "latest",
        interpretation:
          "Connectivity determines whether remote data-collection and platform work are realistic.",
        userVisible: true,
      },
    ],
    opportunities: [
      {
        id: "solar-pump-service",
        title: "Solar pump service assistant",
        sector: "agri equipment",
        opportunityType: "field service",
        iscoGroup: "7412",
        locationFit: "villages with irrigation and solar equipment programs",
        requiredEducation: "Class 10 or ITI-equivalent electrical basics",
        skillKeywords: [
          "repair",
          "diagnosing problems",
          "customer communication",
          "records",
          "tools",
        ],
        demandLevel: 4,
        wageFloorSignal: 3,
        wageFloor: "admin local wage floor",
        growthOutlook: 4,
        automationExposure: 1,
        trainingAccess: 3,
        trainingPathway: "equipment vendor certificate or NGO field-service course",
        sourceIds: ["district-feed", "wdi"],
      },
      {
        id: "agri-input-sales",
        title: "Agri-input sales and service assistant",
        sector: "agricultural retail",
        opportunityType: "formal or cooperative employment",
        iscoGroup: "5223",
        locationFit: "market towns and cooperative networks",
        requiredEducation: "Class 12 preferred; local language fluency required",
        skillKeywords: [
          "customer communication",
          "keeping records",
          "sales",
          "languages",
        ],
        demandLevel: 3,
        wageFloorSignal: 3,
        wageFloor: "admin local wage floor",
        growthOutlook: 3,
        automationExposure: 2,
        trainingAccess: 4,
        trainingPathway: "cooperative onboarding plus inventory and payments training",
        sourceIds: ["district-feed", "ilostat"],
      },
      {
        id: "farm-data-collector",
        title: "Farm data collection enumerator",
        sector: "development and agri data",
        opportunityType: "seasonal contract",
        iscoGroup: "4227",
        locationFit: "requires mobile access and travel to nearby villages",
        requiredEducation: "Class 12, smartphone literacy, local language",
        skillKeywords: [
          "records",
          "customer communication",
          "basic coding",
          "data",
          "languages",
        ],
        demandLevel: 2,
        wageFloorSignal: 2,
        wageFloor: "admin survey-rate sample",
        growthOutlook: 3,
        automationExposure: 3,
        trainingAccess: 3,
        trainingPathway: "enumerator training, digital form practice, supervisor shadowing",
        sourceIds: ["district-feed", "itu"],
      },
    ],
  },
];

export const emptySurveyData: SurveyData = {
  age: null,
  location: "",
  languages: [],
  work_authorization: "",
  availability: "",
  work_mode_preference: "",
  educational_level: "",
  target_outcome: "",
  target_roles: [],
  target_industries: [],
  time_horizon: "",
  priority_tradeoff: "",
  favorite_skill: "",
  current_role_title: "",
  current_industry: "",
  years_experience_total: "",
  years_experience_domain: "",
  skill_confidence: "",
  seniority_level: "",
  team_lead_experience: "",
  key_responsibilities: [],
  informal_experience: "",
  demonstrated_competencies: [],
  skills: [],
};

export const firstSurveyPrompt =
  "Hi, I am Milo. We can do this like a quick conversation. Tell me a little about yourself: what you are good at, what you enjoy doing, and the country you live in. I will pick up the details as we go.";

export const amaraDemoMessages: ChatMessage[] = [
  {
    role: "assistant",
    content: firstSurveyPrompt,
  },
  {
    role: "user",
    content:
      "I am 22 and live outside Accra in Ghana. I speak English fluently and Twi conversationally. I can work locally and remotely. I finished senior high school. I have 2 years of hands-on repair experience. My most fun skill is phone repair. I feel confident with phone repair 4 out of 5. I helped family and neighbors fix phones informally, and I can show that I diagnosed charging problems, replaced screens, talked to customers, kept records of parts and payments, and wrote basic HTML and JavaScript.",
  },
];

export const amaraSurveyData: SurveyData = {
  age: 22,
  location: "Accra, Ghana",
  languages: ["English fluent", "Twi conversational"],
  work_authorization: "Can work locally and remotely",
  availability: "",
  work_mode_preference: "local or remote",
  educational_level: "senior high school",
  target_outcome: "",
  target_roles: [],
  target_industries: [],
  time_horizon: "",
  priority_tradeoff: "",
  favorite_skill: "phone repair",
  current_role_title: "",
  current_industry: "repair services",
  years_experience_total: "2 years",
  years_experience_domain: "2 years in phone repair",
  skill_confidence: "phone repair 4/5",
  seniority_level: "",
  team_lead_experience: "",
  key_responsibilities: [
    "diagnosing charging problems",
    "replacing screens",
    "customer communication",
    "keeping records of parts and payments",
  ],
  informal_experience: "helped family and neighbors fix phones informally",
  demonstrated_competencies: [
    "diagnosing charging problems",
    "replacing screens",
    "customer communication",
    "keeping records of parts and payments",
    "basic HTML and JavaScript coding",
  ],
  skills: [
    "phone repair",
    "diagnosing charging problems",
    "replacing screens",
    "customer communication",
    "keeping records of parts and payments",
    "basic HTML and JavaScript coding",
  ],
};

export const AMARA_DEMO_CACHE_KEY = "skillroute:amara-demo-skill-profile:v1";
